spring:
  datasource:
    url: jdbc:h2:mem:db_dev;MODE=MySQL

custom:
  jwt:
    tokenExpiration:
      access: 1800
      refresh: 14
    secret: test-jwt-secret-key-minimum-32-characters-long-for-hmac-sha256